# Default values for payment-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "sns-payment"
  name: "payment"
  pullPolicy: "Never"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

env:
  - name: NODE_ENV
    value: "production"
  - name: CONFIG_DIR
    value: "/opt/sns/config"
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-conf
        key: redis_password

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

configMap:
  name: "payment-config"
  data:
    config.json: |
      {
        "server_port": 3000,
        "redis_host": "redis",
        "redis_port": 6379
      }

namespace: "sns"

deployment:
  name: "payment"
  labels:
    app: payment
  

podAnnotations: {}

podSecurityContext: 
  fsGroup: 1000
  runAsGroup: 1000
  runAsUser: 1000

securityContext: 
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi


nodeSelector: {}

tolerations: []

affinity: {}


persistence:
  volumeMounts:
  - name: payment-config
    mountPath: "/opt/sns/config"
  volumes:
  - name: payment-config
    configMap:
      name: payment-config
