apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: {{ .Values.appName }}
  clusterIP: None