apiVersion: v1
kind: Namespace
metadata:
  name: sns

---

apiVersion: v1
kind: Secret
metadata:
  name: ingress-cert
  namespace: sns
type: "kubernetes.io/tls"
data:
  tls.crt: ""
  tls.key: ""
  
  