# Default values for sns-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

global:
  serviceAccountName: sns-sa

nodeSelector: {}

tolerations: []

affinity: {}
