apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.deployment.label | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.deployment.label | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  
